const companiesCO2Emissions = [
  { rank: 1, company: "Saudi Aramco", country: "Saudi-Arabien", emissions: 1951 },
    { rank: 2, company: "Gazprom", country: "Russland", emissions: 1138 },
    { rank: 3, company: "National Iranian Oil Company", country: "Iran", emissions: 1036 },
    { rank: 4, company: "Coal India", country: "Indien", emissions: 1025 },
    { rank: 5, company: "China Shenhua Energy", country: "Volksrepublik China", emissions: 1001 },
    { rank: 6, company: "Rosneft", country: "Russland", emissions: 777 },
    { rank: 7, company: "China National Petroleum Corporation", country: "Volksrepublik China", emissions: 625 },
    { rank: 8, company: "Abu Dhabi National Oil Company", country: "Vereinigte Arabische Emirate", emissions: 584 },
    { rank: 9, company: "ExxonMobil", country: "Vereinigte Staaten", emissions: 577 },
    { rank: 10, company: "PEMEX", country: "Mexiko", emissions: 530 },
    { rank: 11, company: "Royal Dutch Shell", country: "Niederlande", emissions: 508 },
    { rank: 12, company: "Sonatrach", country: "Algerien", emissions: 492 },
    { rank: 13, company: "Kuwait Petroleum Corporation", country: "Kuwait", emissions: 478 },
    { rank: 14, company: "BP", country: "Vereinigtes Königreich", emissions: 448 },
    { rank: 15, company: "Qatar Petroleum", country: "Katar", emissions: 414 },
    { rank: 16, company: "Petróleos de Venezuela", country: "Venezuela", emissions: 398 },
    { rank: 17, company: "Peabody Energy", country: "Vereinigte Staaten", emissions: 397 },
    { rank: 18, company: "Iraq National Oil Company", country: "Irak", emissions: 391 },
    { rank: 19, company: "Petrobras", country: "Brasilien", emissions: 382 },
    { rank: 20, company: "Chevron Corporation", country: "Vereinigte Staaten", emissions: 377 },
    { rank: 21, company: "Datong Coal Mining", country: "Volksrepublik China", emissions: 365 },
    { rank: 22, company: "China National Coal", country: "Volksrepublik China", emissions: 350 },
    { rank: 23, company: "Petronas", country: "Malaysia", emissions: 340 },
    { rank: 24, company: "Nigerian National Petroleum Corporation", country: "Nigeria", emissions: 329 },
    { rank: 25, company: "Lukoil", country: "Russland", emissions: 328 },
    { rank: 26, company: "Glencore", country: "Schweiz", emissions: 322 },
    { rank: 27, company: "BHP Group", country: "Australien", emissions: 317 },
    { rank: 27, company: "Shanxi Coking Coal", country: "Volksrepublik China", emissions: 317 },
    { rank: 29, company: "Shandong Energy", country: "Volksrepublik China", emissions: 314 },
    { rank: 30, company: "Total", country: "Frankreich", emissions: 311 },
    { rank: 31, company: "Shaanxi Coal and Chemical Industry", country: "Volksrepublik China", emissions: 296 },
    { rank: 32, company: "Kohleunternehmen (Polen)", country: "Polen", emissions: 291 },
    { rank: 33, company: "Yankuang Group", country: "Volksrepublik China", emissions: 256 },
    { rank: 34, company: "Arch Coal", country: "Vereinigte Staaten", emissions: 232 },
    { rank: 35, company: "Eni", country: "Italien", emissions: 231 },
    { rank: 35, company: "Equinor", country: "Norwegen", emissions: 231 },
    { rank: 37, company: "Türkmengaz", country: "Turkmenistan", emissions: 230 },
    { rank: 38, company: "ConocoPhillips", country: "Vereinigte Staaten", emissions: 224 },
    { rank: 39, company: "Kohleunternehmen (Kasachstan)", country: "Kasachstan", emissions: 222 },
    { rank: 40, company: "SUEK", country: "Russland", emissions: 218 },
    { rank: 41, company: "Henan Energy and Chemical Industry", country: "Volksrepublik China", emissions: 215 },
    { rank: 41, company: "Anglo American", country: "Vereinigtes Königreich", emissions: 215 },
    { rank: 43, company: "Jizhong Energy", country: "Volksrepublik China", emissions: 213 },
    { rank: 44, company: "Surgutneftegas", country: "Russland", emissions: 212 },
    { rank: 45, company: "Shanxi Jincheng Anthracite Coal Mining", country: "Volksrepublik China", emissions: 204 },
    { rank: 46, company: "Bumi Resources", country: "Indonesien", emissions: 200 },
    { rank: 47, company: "Sinopec", country: "Volksrepublik China", emissions: 197 },
    { rank: 48, company: "Kailuan Group", country: "Volksrepublik China", emissions: 192 },
    { rank: 49, company: "China National Offshore Oil", country: "Volksrepublik China", emissions: 187 },
    { rank: 50, company: "Shanxi Lu’an Mining", country: "Volksrepublik China", emissions: 181 }
];


export default companiesCO2Emissions;

/* 
Quelle : Liste der fördernden Unternehmen nach Treibhausgas-Emissionen. (2015). Von Wikipedia: https://de.wikipedia.org/wiki/Liste_der_f%C3%B6rdernden_Unternehmen_nach_Treibhausgas-Emissionen abgerufen.
*/
